### ISSUE TITLE
chpt09 tls_client.exe

### ISSUE THREAD

**Issue by BeneficialCode** [codeplea/Hands-On-Network-Programming-with-C#12]
I compile it and  run it. when it run to _kbhit(), the function return false. Then it's cause program block in SSL_read().

**Comment by codeplea** [comment]
Which operating system and compiler are you using?

What command line terminal are you using?

What server are you connecting the tls_client to?

**Comment by BeneficialCode** [comment]
windows 10 gcc mingw

**Comment by codeplea** [comment]
What server are you connecting the tls_client to?

Can you try connecting to example.com on port 443 and report back if you get the same error?

How do you know it is stuck on SSL_read()?

**Comment by BeneficialCode** [comment]
I add three code : printf("_kbhit() before\n");、//printf("read before\n");、//printf("_kbhit() before\n");
I found that if(_kbhit()) is false. Then execute to the SSL_read(). The program is not execute the terminal input code.

**Comment by BeneficialCode** [comment]
![Uploading bug5.png…]()

**Comment by BeneficialCode** [comment]
![bug5](https://user-images.githubusercontent.com/40847073/121842186-863a3880-cd12-11eb-8d5e-b022ad38f64e.png)

**Comment by codeplea** [comment]
I found out what was happening. In some cases, `select()` will indicate that data is available to be read from the socket, but the data is just TLS "bookkeeping" and not actual application-level data. Then when `SSL_read()` is called it will block until some actual application-level data comes. This data never comes, because the TLS server is expecting the client to send a request first.

This can be fixed by enabling non-blocking sockets. Then `SSL_read()` will always return quickly. The return value of it must be checked carefully to determine if there is no new data or if the socket has been closed.

I have updated the `tls_client.c` file. Can you please download it and test it? Please let me know if it works for you now.

Thanks for bringing this to my attention. Sorry for the mistake.

I will try to update the errata list at: https://handsonnetworkprogramming.com/errata/ in the next few days.

**Comment by BeneficialCode** [comment]
It works correctly now. Thanks for your help : )
